site_name: Grizabella
site_url: https://pwilkin.github.io/grizabella/
repo_url: https://github.com/pwilkin/grizabella
repo_name: pwilkin/grizabella
theme: material
docs_dir: docs/user_guide
watch:
  - grizabella
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: true
nav:
  - Home: index.md
  - Installation: installation.md
  - Getting Started: getting_started.md
  - Core Concepts: core_concepts.md
  - Python API Detailed Guide: python_api_detailed.md
  - MCP Server API Guide: mcp_server_api_guide.md
  - PySide6 UI Guide: pyside6_ui_guide.md
  - API Reference:
    - Core Models: api/core_models.md
    - Query Models: api/query_models.md
    - API Client: api/client.md
    - MCP Server: api/mcp_server.md
  - Troubleshooting & FAQ: troubleshooting_faq.md